services:
  gitlab:
    image: gitlab/gitlab-ce:19.4.1-ce.0
    container_name: demo-gitlab
    hostname: gitlab.localhost
    restart: unless-stopped
    shm_size: "256m"

    ports:
      - "8080:80"
      - "2222:22"

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8080'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

        gitlab_rails['nginx']['listen_port'] = 80
        gitlab_rails['nginx']['listen_https'] = false

        puma['worker_processes'] = 2
        sidekiq['max_concurrency'] = 5
        gitlab_rails['monitoring_whitelist'] = [
          '127.0.0.0/8',
          '::1/128',
          '172.25.0.1/32'
        ]

    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost/-/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 180s

  gitlab-runner:
    image: gitlab/gitlab-runner:18.10.1
    container_name: demo-gitlab-runner
    restart: unless-stopped
    depends_on:
      gitlab:
        condition: service_healthy
    volumes:
      - runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  runner-config:
